# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - divanvardiya

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up Python version 3.11
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Create and activate virtual environment
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      
      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # List files before zipping to ensure all files are in place
      - name: List files before zipping
        run: ls -R
        
      # Zip the codebase, excluding the virtual environment directory
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      # Upload the zipped artifact to use it in the deployment job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # List files after unzipping to ensure everything is correctly unzipped
      - name: List files after unzip
        run: ls -R

      # Deploy to Azure Web App using the publish profile stored in secrets
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'divanvardiya'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0176FA62E503469489322A3086E4F600 }}
